package F0;

import android.R;

/* loaded from: classes.dex */
public abstract class a {
    public static int ColorStateListItem_alpha = 3;
    public static int ColorStateListItem_android_alpha = 1;
    public static int ColorStateListItem_android_color = 0;
    public static int ColorStateListItem_android_lStar = 2;
    public static int ColorStateListItem_lStar = 4;
    public static int FontFamilyFont_android_font = 0;
    public static int FontFamilyFont_android_fontStyle = 2;
    public static int FontFamilyFont_android_fontVariationSettings = 4;
    public static int FontFamilyFont_android_fontWeight = 1;
    public static int FontFamilyFont_android_ttcIndex = 3;
    public static int FontFamilyFont_font = 5;
    public static int FontFamilyFont_fontStyle = 6;
    public static int FontFamilyFont_fontVariationSettings = 7;
    public static int FontFamilyFont_fontWeight = 8;
    public static int FontFamilyFont_ttcIndex = 9;
    public static int FontFamily_fontProviderAuthority = 0;
    public static int FontFamily_fontProviderCerts = 1;
    public static int FontFamily_fontProviderFetchStrategy = 2;
    public static int FontFamily_fontProviderFetchTimeout = 3;
    public static int FontFamily_fontProviderPackage = 4;
    public static int FontFamily_fontProviderQuery = 5;
    public static int FontFamily_fontProviderSystemFontFamily = 6;
    public static int GradientColorItem_android_color = 0;
    public static int GradientColorItem_android_offset = 1;
    public static int GradientColor_android_centerColor = 7;
    public static int GradientColor_android_centerX = 3;
    public static int GradientColor_android_centerY = 4;
    public static int GradientColor_android_endColor = 1;
    public static int GradientColor_android_endX = 10;
    public static int GradientColor_android_endY = 11;
    public static int GradientColor_android_gradientRadius = 5;
    public static int GradientColor_android_startColor = 0;
    public static int GradientColor_android_startX = 8;
    public static int GradientColor_android_startY = 9;
    public static int GradientColor_android_tileMode = 6;
    public static int GradientColor_android_type = 2;
    public static int RecyclerView_android_clipToPadding = 1;
    public static int RecyclerView_android_descendantFocusability = 2;
    public static int RecyclerView_android_orientation = 0;
    public static int RecyclerView_fastScrollEnabled = 3;
    public static int RecyclerView_fastScrollHorizontalThumbDrawable = 4;
    public static int RecyclerView_fastScrollHorizontalTrackDrawable = 5;
    public static int RecyclerView_fastScrollVerticalThumbDrawable = 6;
    public static int RecyclerView_fastScrollVerticalTrackDrawable = 7;
    public static int RecyclerView_layoutManager = 8;
    public static int RecyclerView_reverseLayout = 9;
    public static int RecyclerView_spanCount = 10;
    public static int RecyclerView_stackFromEnd = 11;
    public static int ViewPager2_android_orientation;
    public static int[] ColorStateListItem = {R.attr.color, R.attr.alpha, R.attr.lStar, com.korail.talk.R.attr.alpha, com.korail.talk.R.attr.lStar};
    public static int[] FontFamily = {com.korail.talk.R.attr.fontProviderAuthority, com.korail.talk.R.attr.fontProviderCerts, com.korail.talk.R.attr.fontProviderFetchStrategy, com.korail.talk.R.attr.fontProviderFetchTimeout, com.korail.talk.R.attr.fontProviderPackage, com.korail.talk.R.attr.fontProviderQuery, com.korail.talk.R.attr.fontProviderSystemFontFamily};
    public static int[] FontFamilyFont = {R.attr.font, R.attr.fontWeight, R.attr.fontStyle, R.attr.ttcIndex, R.attr.fontVariationSettings, com.korail.talk.R.attr.font, com.korail.talk.R.attr.fontStyle, com.korail.talk.R.attr.fontVariationSettings, com.korail.talk.R.attr.fontWeight, com.korail.talk.R.attr.ttcIndex};
    public static int[] GradientColor = {R.attr.startColor, R.attr.endColor, R.attr.type, R.attr.centerX, R.attr.centerY, R.attr.gradientRadius, R.attr.tileMode, R.attr.centerColor, R.attr.startX, R.attr.startY, R.attr.endX, R.attr.endY};
    public static int[] GradientColorItem = {R.attr.color, R.attr.offset};
    public static int[] RecyclerView = {R.attr.orientation, R.attr.clipToPadding, R.attr.descendantFocusability, com.korail.talk.R.attr.fastScrollEnabled, com.korail.talk.R.attr.fastScrollHorizontalThumbDrawable, com.korail.talk.R.attr.fastScrollHorizontalTrackDrawable, com.korail.talk.R.attr.fastScrollVerticalThumbDrawable, com.korail.talk.R.attr.fastScrollVerticalTrackDrawable, com.korail.talk.R.attr.layoutManager, com.korail.talk.R.attr.reverseLayout, com.korail.talk.R.attr.spanCount, com.korail.talk.R.attr.stackFromEnd};
    public static int[] ViewPager2 = {R.attr.orientation};
}
