package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.Status;
import g2.AbstractC5547i;
import i2.AbstractC5683p;
import java.util.concurrent.TimeUnit;

/* loaded from: classes.dex */
public final class e0 extends AbstractC5547i {

    /* renamed from: a, reason: collision with root package name */
    private final Status f12021a;

    public e0(Status status) {
        AbstractC5683p.checkNotNull(status, "Status must not be null");
        AbstractC5683p.checkArgument(!status.isSuccess(), "Status must not be success");
        this.f12021a = status;
    }

    final Status a() {
        return this.f12021a;
    }

    @Override // g2.AbstractC5547i
    public final void addStatusListener(AbstractC5547i.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final g2.n await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final void setResultCallback(g2.o oVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final <S extends g2.n> g2.r then(g2.q qVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final g2.n await(long j8, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // g2.AbstractC5547i
    public final void setResultCallback(g2.o oVar, long j8, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
