package r4;

import z4.z;

/* loaded from: classes.dex */
public class g {
    public static final String COMMON_PARAMETER = "Device=AD&Version=250601001&Key=korail1234567890";
    public static final int CONNECTION_TIMEOUT = 60000;
    public static final String DELAY_REFUND_DETAIL_INFO_POST_DATA = "bbrdId=000000000033&OffSet=0&ptwtSqno=51";
    public static final String HOST_DEV = "mobiledev.letskorail.com";
    public static final String HOST_REAL = "smart.letskorail.com";
    public static final String HOST_REAL_MULTI_LANG = "www.korail.com";
    public static final String HOST_REAL_MULTI_LANG_HOST_TEST = "dev5.letskorail.com";
    public static final String HOST_STAGING = "dev2.letskorail.com";
    public static final String HOST_TEST = "dev3.letskorail.com";
    public static final int IMAGE_CONNECTION_TIMEOUT = 10000;
    public static final int IMAGE_READ_TIMEOUT = 10000;
    public static final String LIMOUSINE_HOST_URL = "https://blog.naver.com/korailblog/";
    public static final String LIMOUSINE_INFORMATION_URL = "https://blog.naver.com/korailblog/223673675369?trackingCode=blog_bloghome_searchlist";
    public static final String LOST_112_URL = "https://m.lost112.go.kr/";
    public static final String MULTI_LANGUAGE_AFTER_DATA = "/ticket/reservation";
    public static final String MULTI_LANGUAGE_CHN_DATA = "chn/ticket/reservation";
    public static final String MULTI_LANGUAGE_ENG_DATA = "eng/ticket/reservation";
    public static final String MULTI_LANGUAGE_ID_DATA = "id/ticket/reservation";
    public static final String MULTI_LANGUAGE_JPN_DATA = "jpn/ticket/reservation";
    public static final String MULTI_LANGUAGE_TH_DATA = "th/ticket/reservation";
    public static final String MULTI_LANGUAGE_TW_DATA = "tw/ticket/reservation";
    public static final String MULTI_LANGUAGE_VI_DATA = "vi/ticket/reservation";
    public static final String NAVER_REQUEST_API = "https://openapi.naver.com/v1/nid/me";
    public static final String NETFUNNEL_ACTION_ID = "act_8";
    public static final String NETFUNNEL_ACTION_ID_PEAKSEASON = "act_8_2";
    public static final String NETFUNNEL_ACTION_PAY_ID = "act_18";
    public static final String NETFUNNEL_ACTION_PRODUCT_ID = "act_6";
    public static final String NETFUNNEL_ACTION_RESERVED_ID = "act_21";
    public static final String NETFUNNEL_ACTION_RESERVE_ID = "act_14";
    public static final String NETFUNNEL_ACTION_TEST_ID = "act_4";
    public static final String NETFUNNEL_SERVER_ID = "service_1";
    public static final String N_CARD_CAUTION_URL = "https://smart.letskorail.com/returninfo/html/ncard_guide02.html";
    public static final String N_CARD_INFO_URL = "https://smart.letskorail.com/returninfo/html/ncard_guide03.html";
    public static final String N_CARD_PURCHARE_INFO_URL = "https://smart.letskorail.com/returninfo/html/ncard_guide01.html";
    public static final String PRIVACY_URL = "https://info.korail.com/info/contents.do?key=2812";
    public static final String PRODUCT_MAAS_RECEIPT_POST_DATA = "qry_dv_val=M&add_srv_req_no=";
    public static final String PRODUCT_MAAS_RECEIPT_POST_DATA_PNR = "qry_dv_val=E&add_srv_req_no=";
    public static final String PRODUCT_POST_DATA = "pnrNo=";
    public static final String PRODUCT_RECEIPT_POST_DATA = "qry_dv_val=B&";
    public static final String PUSH_APPTYPE = "korailtalk";
    public static final String PUSH_DEV = "dev.letskorail.com";
    public static final String PUSH_PORT = "3101";
    public static final String PUSH_REAL = "smart.letskorail.com";
    public static final String PUSH_STAGING = "smartbeta.letskorail.com";
    public static final int READ_TIMEOUT = 60000;
    public static final String SECURE_PROTOCOL = "https://";
    public static final String TIDS_PARAM = "dptRsStnCd";
    public static final String TRAIN_MAP_URL = "https://gis.korail.com/korailTalk/entrance";
    public static final String TRIP_QR_AUTH_LOCATION_URL = "https://smart.letskorail.com/ebizcom/event/tourist/EbizcomEvtTourWcus06701_detail.do?searchKeyword2=271";
    public static final String TRIP_QR_AUTH_PRODUCT_URL = "https://smart.letskorail.com/ebizcom/event/tourist/EbizcomEvtTourWcus06701_detail.do?searchKeyword2=270";
    public static final K4.a SERVER_TYPE = K4.a.fromCode("3");
    public static final String SIGN_UP_URL = z.getWebHost() + "/ebizmk/member/mk_join_member.do";
    public static final String FIND_MEMBER_ID_URL = z.getWebHost() + "/ebizmk/member/mk_check_member.do";
    public static final String FIND_MEMBER_PW_URL = z.getWebHost() + "/ebizmk/member/mk_pass_member.do";
    public static final String TOUR_PACKAGE_URL = z.getWebHost() + "/ebizmk/prd/main.do";
    public static final String NOTICE_URL = z.getWebHost() + "/ebizmk/notice/list_plus.do";
    public static final String NOTICE_DETAIL_URL = z.getWebHost() + "/ebizmk/notice/detail.do";
    public static final String GUIDE_URL = z.getWebHost() + "/ebizmk/qna/list_plus.do";
    public static final String VOUCHER_URL = z.getWebHost() + "/ebizmk/prd/voucher.do";
    public static final String PARTNER_URL = z.getWebHost() + "/ebizmw/w_adv03105.do";
    public static final String CMTR_INFO_URL = z.getWebHost() + "/docs/hc/hc12200/cmtr_tos.html?tabId=1";
    public static final String DELAY_REFUND_DETAIL_INFO_URL = z.getWebHost() + "/ebizmk/notice/detail.do";
    public static final String MULTI_LANGUAGE_URL = z.getMultiLangWebHost() + "/global/";
    public static final String COMMISSION_URL = z.getWebHost() + "/returninfo/html/returnchginfo.html";
    public static final String LIMOUSINE_COMMISSION_URL = z.getWebHost() + "/returninfo/html/returnchginfo.html?tabId=4";
    public static final String BELONGINGS_URL = z.getWebHost() + "/returninfo/html/luggageinfo.html";
    public static final String PRODUCT_URL = z.getWebHost() + "/ebizprd/EbizPrdSrvcListView.do";
    public static final String PRODUCT_RECEIPT_URL = z.getWebHost() + "/ebizprd/EbizPrdTicketPr13500w_pr13571_new.do";
    public static final String PRODUCT_MAAS_RECEIPT_URL = z.getWebHost() + "/ebizprd/EbizPrdTicketPr13500w_pr13571_new.do";
    public static final String CONVENIENCE_SETTING_URL = z.getWebHost() + "/korail/com/mypage/preset/m_preset_list.do";
    public static final String IDENTITY_VERIFICATION_URL = z.getWebHost() + "/classes/com.korail.mobile.certification.MCertify.do";
    public static final String TERMS_URL = z.getWebHost() + "/ticket/guest/ktxService";
    public static final String PHONE_AUTH_URL = z.getWebHost() + "/classes/com.korail.mobile.mypage.mCertify.do";
    public static final String WHEELCHAIR_TOOLS_URL = z.getWebHost() + "/docs/guide/chairinfo.html";
    public static final String TIDS_URL = z.getWebHost() + "/ebiztids/EbizTidsList.do";
}
