package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import j2.AbstractC5814a;
import j2.AbstractC5816c;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* renamed from: com.google.android.gms.internal.ads.zq, reason: case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C5141zq extends AbstractC5814a {
    public static final Parcelable.Creator<C5141zq> CREATOR = new C1159Aq();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final H1.Z0 zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final C3197im zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final H1.Y1 zzc;
    public final H1.d2 zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final L1.a zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final C1840Ri zzy;
    public final List zzz;

    C5141zq(int i8, Bundle bundle, H1.Y1 y12, H1.d2 d2Var, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, L1.a aVar, Bundle bundle2, int i9, List list, Bundle bundle3, boolean z8, int i10, int i11, float f8, String str5, long j8, String str6, List list2, String str7, C1840Ri c1840Ri, List list3, long j9, String str8, float f9, boolean z9, int i12, int i13, boolean z10, String str9, String str10, boolean z11, int i14, Bundle bundle4, String str11, H1.Z0 z02, boolean z12, Bundle bundle5, String str12, String str13, String str14, boolean z13, List list4, String str15, List list5, int i15, boolean z14, boolean z15, boolean z16, ArrayList arrayList, String str16, C3197im c3197im, String str17, Bundle bundle6) {
        this.zza = i8;
        this.zzb = bundle;
        this.zzc = y12;
        this.zzd = d2Var;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = aVar;
        this.zzl = bundle2;
        this.zzm = i9;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z8;
        this.zzq = i10;
        this.zzr = i11;
        this.zzs = f8;
        this.zzt = str5;
        this.zzu = j8;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = c1840Ri;
        this.zzA = j9;
        this.zzB = str8;
        this.zzC = f9;
        this.zzH = z9;
        this.zzD = i12;
        this.zzE = i13;
        this.zzF = z10;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z11;
        this.zzK = i14;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = z02;
        this.zzO = z12;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z13;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i15;
        this.zzY = z14;
        this.zzZ = z15;
        this.zzaa = z16;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = c3197im;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i8) {
        int i9 = this.zza;
        int iBeginObjectHeader = AbstractC5816c.beginObjectHeader(parcel);
        AbstractC5816c.writeInt(parcel, 1, i9);
        AbstractC5816c.writeBundle(parcel, 2, this.zzb, false);
        AbstractC5816c.writeParcelable(parcel, 3, this.zzc, i8, false);
        AbstractC5816c.writeParcelable(parcel, 4, this.zzd, i8, false);
        AbstractC5816c.writeString(parcel, 5, this.zze, false);
        AbstractC5816c.writeParcelable(parcel, 6, this.zzf, i8, false);
        AbstractC5816c.writeParcelable(parcel, 7, this.zzg, i8, false);
        AbstractC5816c.writeString(parcel, 8, this.zzh, false);
        AbstractC5816c.writeString(parcel, 9, this.zzi, false);
        AbstractC5816c.writeString(parcel, 10, this.zzj, false);
        AbstractC5816c.writeParcelable(parcel, 11, this.zzk, i8, false);
        AbstractC5816c.writeBundle(parcel, 12, this.zzl, false);
        AbstractC5816c.writeInt(parcel, 13, this.zzm);
        AbstractC5816c.writeStringList(parcel, 14, this.zzn, false);
        AbstractC5816c.writeBundle(parcel, 15, this.zzo, false);
        AbstractC5816c.writeBoolean(parcel, 16, this.zzp);
        AbstractC5816c.writeInt(parcel, 18, this.zzq);
        AbstractC5816c.writeInt(parcel, 19, this.zzr);
        AbstractC5816c.writeFloat(parcel, 20, this.zzs);
        AbstractC5816c.writeString(parcel, 21, this.zzt, false);
        AbstractC5816c.writeLong(parcel, 25, this.zzu);
        AbstractC5816c.writeString(parcel, 26, this.zzv, false);
        AbstractC5816c.writeStringList(parcel, 27, this.zzw, false);
        AbstractC5816c.writeString(parcel, 28, this.zzx, false);
        AbstractC5816c.writeParcelable(parcel, 29, this.zzy, i8, false);
        AbstractC5816c.writeStringList(parcel, 30, this.zzz, false);
        AbstractC5816c.writeLong(parcel, 31, this.zzA);
        AbstractC5816c.writeString(parcel, 33, this.zzB, false);
        AbstractC5816c.writeFloat(parcel, 34, this.zzC);
        AbstractC5816c.writeInt(parcel, 35, this.zzD);
        AbstractC5816c.writeInt(parcel, 36, this.zzE);
        AbstractC5816c.writeBoolean(parcel, 37, this.zzF);
        AbstractC5816c.writeString(parcel, 39, this.zzG, false);
        AbstractC5816c.writeBoolean(parcel, 40, this.zzH);
        AbstractC5816c.writeString(parcel, 41, this.zzI, false);
        AbstractC5816c.writeBoolean(parcel, 42, this.zzJ);
        AbstractC5816c.writeInt(parcel, 43, this.zzK);
        AbstractC5816c.writeBundle(parcel, 44, this.zzL, false);
        AbstractC5816c.writeString(parcel, 45, this.zzM, false);
        AbstractC5816c.writeParcelable(parcel, 46, this.zzN, i8, false);
        AbstractC5816c.writeBoolean(parcel, 47, this.zzO);
        AbstractC5816c.writeBundle(parcel, 48, this.zzP, false);
        AbstractC5816c.writeString(parcel, 49, this.zzQ, false);
        AbstractC5816c.writeString(parcel, 50, this.zzR, false);
        AbstractC5816c.writeString(parcel, 51, this.zzS, false);
        AbstractC5816c.writeBoolean(parcel, 52, this.zzT);
        AbstractC5816c.writeIntegerList(parcel, 53, this.zzU, false);
        AbstractC5816c.writeString(parcel, 54, this.zzV, false);
        AbstractC5816c.writeStringList(parcel, 55, this.zzW, false);
        AbstractC5816c.writeInt(parcel, 56, this.zzX);
        AbstractC5816c.writeBoolean(parcel, 57, this.zzY);
        AbstractC5816c.writeBoolean(parcel, 58, this.zzZ);
        AbstractC5816c.writeBoolean(parcel, 59, this.zzaa);
        AbstractC5816c.writeStringList(parcel, 60, this.zzab, false);
        AbstractC5816c.writeString(parcel, 61, this.zzac, false);
        AbstractC5816c.writeParcelable(parcel, 63, this.zzad, i8, false);
        AbstractC5816c.writeString(parcel, 64, this.zzae, false);
        AbstractC5816c.writeBundle(parcel, 65, this.zzaf, false);
        AbstractC5816c.finishObjectHeader(parcel, iBeginObjectHeader);
    }
}
